# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gone Mobile Podcast
email: gonemobilecast@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gone Mobile is a podcast discussing the latest in mobile development, with a healthy bias towards Xamarin technologies.  The podcast covers in-depth topics with guests ranging from Android, iOS, Windows Phone & Store development to mobile marketing and design, as well as other mobile or not so mobile related technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gonemobile.io" # the base hostname & protocol for your site
twitter_username: GoneMobileCast
#github_username:  gonemobile

# Build settings
markdown: kramdown

root: /
permalink: /blog/:title/

# Google Analytics
google_analytics_tracking_id: UA-6465612-22

disqus_short_name: gonemobile
disqus_show_comment_count: true

